// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejitiblrqntfuwihodzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqaXRpYmxycW50ZnV3aWhvZHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTU1MzMsImV4cCI6MjA2NDM5MTUzM30.60RjmYuU68Ah8Wj07_H_FBWYtAYbOaWpxpXgopFXmi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);